#Configuraci?n del Simulador de Supermercado
#Fri Jun 19 16:56:20 GMT-04:00 2026
articulos.cliente.max=50
articulos.cliente.min=1
duracion.real.segundos=20
limite.cliente.rapido=10
limite.clientes=0
mostrar.detalle.clientes=true
mostrar.estadisticas.avanzadas=true
num.cajas.normales=4
num.cajas.rapidas=1
probabilidad.llegada.cliente=100
tiempo.caja.normal.max=19
tiempo.caja.normal.min=5
tiempo.caja.rapida.max=5
tiempo.caja.rapida.min=3
tiempo.simulado.horas=24
