#Configuracion del Simulador de Supermercado
#Mon Jun 29 11:52:53 GMT-04:00 2026
articulos.cliente.max=40
articulos.cliente.min=1
duracion.real.segundos=20
limite.cliente.rapido=12
limite.clientes=0
mostrar.detalle.clientes=true
mostrar.estadisticas.avanzadas=true
num.cajas.normales=4
num.cajas.rapidas=1
probabilidad.llegada.cliente=45
tiempo.caja.normal.max=9
tiempo.caja.normal.min=5
tiempo.caja.rapida.max=6
tiempo.caja.rapida.min=3
tiempo.simulado.horas=1
